name: DEV-GOHUBLY-DESIGN-SYSTEM-DEPLOY

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main, development]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 14.17.x

      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      # - name: Azure Artifacts - Feed authentication
      #   run: npx vsts-npm-auth -config .npmrc

      - name: Install npm packages üîß
        run: yarn

  build:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Build Storybook üîß
        run: yarn build:storybook

      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: development # The branch the action should deploy to.
          FOLDER: storybook-static # The folder that the build-storybook script generates files.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          TARGET_FOLDER: src

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: development # The branch the action should deploy to.
          FOLDER: storybook-static # The folder that the build-storybook script generates files.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          TARGET_FOLDER: src
