name: DEV CI/CD GoHubly Design-System

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main, development]

jobs:
  setup-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup NodeJS ğŸ”§
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 14.17.x

      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      # - name: Azure Artifacts - Feed authentication
      #   run: npx vsts-npm-auth -config .npmrc

      - name: Install npm packages ğŸ”§
        run: yarn

      - name: Build Storybook ğŸ”§
        run: yarn build:storybook

  deploy:
    runs-on: ubuntu-latest
    needs: [setup-and-build]
    steps:
      - name: Package listing ğŸ›ï¸ğŸ›ï¸ğŸ›ï¸
        run: ls

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: development # The branch the action should deploy to.
          folder: storybook-static # The folder the action should deploy.
