name: DEV-GOHUBLY-DESIGN-SYSTEM-DEPLOY

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main, development]

jobs:
  setup-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 14.17.x

      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      # - name: Azure Artifacts - Feed authentication
      #   run: npx vsts-npm-auth -config .npmrc

      - name: Install npm packages ğŸ”§
        run: yarn

      - name: Build Storybook ğŸ”§
        run: yarn build:storybook

  deploy:
    runs-on: ubuntu-latest
    needs: [setup-and-build]
    steps:
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: development # The branch the action should deploy to.
          FOLDER: storybook-static # The folder that the build-storybook script generates files.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          TARGET_FOLDER: src
